services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.133.0
    container_name: otel-collector
    command: ["--config=/etc/otel/collector-config.yml"]
    volumes:
      - ./docker-volume/collector-config.yaml:/etc/otel/collector-config.yml
    ports:
      - "4317:4317"
  loki:
    image: grafana/loki:3.5.3
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./docker-volume/loki.yaml:/etc/loki/loki-config.yaml
    depends_on:
      - otel-collector
  tempo:
    image: grafana/tempo:2.8.2
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker-volume/tempo.yaml:/etc/tempo.yaml
    depends_on:
      - otel-collector
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - ./docker-volume/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
  grafana:
    image: grafana/grafana:12.0
    container_name: grafana
    volumes:
      - ./docker-volume/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - prometheus
      - tempo